alias gadd="git add . ; git add -u"
alias gco="git checkout"
alias gcommit="git commit --amend --no-edit"
alias gpush="git push origin head -f"
alias gst="git status"
alias gpro="git pull --rebase origin master"
