require 'rake'
require 'erb'

desc "install the dot files into user's home directory"
task :install do
  install_rvm
  install_homebrew
  install_oh_my_zsh
  install_janus

  replace_all = false
  files = Dir['*'] - %w[Rakefile README.rdoc LICENSE oh-my-zsh]

  files.each do |file|
    system %Q{mkdir -p "$HOME/.#{File.dirname(file)}"} if file =~ /\//
    if File.exist?(File.join(ENV['HOME'], ".#{file.sub(/\.erb$/, '')}"))
      if File.identical? file, File.join(ENV['HOME'], ".#{file.sub(/\.erb$/, '')}")
        puts "identical ~/.#{file.sub(/\.erb$/, '')}"
      elsif replace_all
        replace_file(file)
      else
        print "overwrite ~/.#{file.sub(/\.erb$/, '')}? [ynaq] "
        case $stdin.gets.chomp
        when 'a'
          replace_all = true
          replace_file(file)
        when 'y'
          replace_file(file)
        when 'q'
          exit
        else
          puts "skipping ~/.#{file.sub(/\.erb$/, '')}"
        end
      end
    else
      link_file(file)
    end
  end
end

def install_rvm
  print "install rvm? [ynq] "
  case $stdin.gets.chomp
  when 'y'
    # https://rvm.io
    puts "installing rvm"
    system %Q{gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3}
    system %Q{\curl -sSL https://get.rvm.io | bash -s stable}
  when 'q'
    exit
  else
    puts "skipping rvm"
  end
end

def install_homebrew
  print "install homebrew? [ynq] "
  case $stdin.gets.chomp
  when 'y'
    # brew.sh
    puts "installing homebrew"
    system %Q{ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"}
  when 'q'
    exit
  else
    puts "skipping homebrew"
  end
end

def install_oh_my_zsh
  print "install oh-my-zsh? [ynq] "
  case $stdin.gets.chomp
  when 'y'
    puts "installing oh-my-zsh"
    system %Q{sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"}
  when 'q'
    exit
  else
    puts "skipping oh-my-zsh, you will need to change ~/.zshrc"
  end
end

def install_janus
  print "install Vim custom distritbution Janus? [ynq] "
  case $stdin.gets.chomp
  when 'y'
    puts "installing oh-my-zsh"
    system %Q{curl -Lo- https://bit.ly/janus-bootstrap | bash}
  when 'q'
    exit
  else
    puts "skipping janus"
  end
end

private

def replace_file(file)
  system %Q{rm -rf "$HOME/.#{file.sub(/\.erb$/, '')}"}
  link_file(file)
end

def link_file(file)
  if file =~ /.erb$/
    puts "generating ~/.#{file.sub(/\.erb$/, '')}"
    File.open(File.join(ENV['HOME'], ".#{file.sub(/\.erb$/, '')}"), 'w') do |new_file|
      new_file.write ERB.new(File.read(file)).result(binding)
    end
  elsif file =~ /zshrc$/ # copy zshrc instead of link
    puts "copying ~/.#{file}"
    system %Q{cp "$PWD/#{file}" "$HOME/.#{file}"}
  else
    puts "linking ~/.#{file}"
    system %Q{ln -s "$PWD/#{file}" "$HOME/.#{file}"}
  end
end

