set winwidth=90
set winminwidth=15
set winheight=5
set winminheight=5
set winheight=999

let mapleader = ","
nmap <leader>n :NERDTree<cr>
" RSpec.vim mappings
map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>
