hello:
	echo "Please provide specific task to run"
git-config:
	git config --global user.email "shen.marshall@gmail.com"
	git config --global user.name "Marshall Shen"
alias:
	cp git-alias.sh ~/.alias

# Automate
# 	- zsh
#    - sudo apt-get install zsh
#    - sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)

# Automate
# Vim Janus install
# 	- sudo apt-get install vim-gnome
# 	- curl -Lo- https://bit.ly/janus-bootstrap | bash

#Automate
#
#  git config --global user.email "you@example.com"
#	 git config --global user.name "Your Name"

